import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Sidebar from '~/components/SidebarMenu';
import { Storage, Questions, Mail, Links, Ball, Plus } from '~/icons';
import Link from 'next/link';
import Script from 'next/script';
import AccessProvider from '~/contexts/AccessContext';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IPermissionsResponse {
  type: number;
  name: string;
  description: string;
  ruleName: null;
  data: any;
  createdAt: number;
  updatedAt: number;
}

async function getUserPermissions() {
  const response = await fetch(
    'https://api.crm.staging.arbatdeport.life/v2/access/get-user-permissions',
    {
      method: 'GET',
      headers: { 'X-Api-Key': 'IoOFarIAxjFRLgjJSYONgd6Y7gx50epd' },
    },
  );

  const data = (await response.json()) as unknown as Record<
    string,
    IPermissionsResponse
  >;

  return Object.values(data).map((item) => item.name);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const permissions = await getUserPermissions();

  return (
    <html lang="ru">
      <body style={manrope.style}>
        <div className="h-screen w-full overflow-hidden">
          <AccessProvider permissions={permissions}>
            <div className="relative flex h-screen w-full overflow-hidden">
              <Sidebar />
              <main className="relative flex h-full w-full flex-col overflow-hidden bg-[#F1F3F7]">
                <div className="z-[15]">
                  <div className="z-10 flex w-full items-center justify-between bg-white px-6 py-3">
                    <div className="">header</div>
                    <div className="flex items-center">
                      <div className="mr-6 flex items-center gap-x-6">
                        <Link href="https://disk.yandex.ru/d/tKpzWq2XQxjJKQ">
                          <Storage className="hover:text-[#3B82F6]" />
                        </Link>
                        <Questions className="hover:text-[#3B82F6]" />
                        <Mail className="hover:text-[#3B82F6]" />
                        <Links className="hover:text-[#3B82F6]" />
                        <Ball className="hover:text-[#3B82F6]" />
                        <Plus className="hover:text-[#3B82F6]" />
                      </div>
                      <div className="h-10 w-10 rounded-full border border-[#3B82F6]"></div>
                    </div>
                  </div>
                </div>
                <div className="h-full w-full overflow-hidden">
                  <div className="relative h-full w-full overflow-x-hidden overflow-y-scroll">
                    <div className="vertical-scrollbar scrollbar-lg flex h-full w-full flex-col space-y-7 overflow-y-auto px-6 py-8">
                      {children}
                    </div>
                  </div>
                </div>
              </main>
            </div>
          </AccessProvider>
        </div>

        <Script
          src={`/yandex?lang=ru_RU&apikey=dfdb4b36-0feb-4305-a54d-ec40caddfd5b`}
          type="module"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
