import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '~/components/SidebarMenu';
import { Storage, Questions, Mail, Links, Ball, Plus } from '~/icons';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body style={inter.style}>
        <div className="h-screen w-full overflow-hidden">
          <div className="relative flex h-screen w-full overflow-hidden">
            <Sidebar />
            <main className="relative flex h-full w-full flex-col overflow-hidden bg-[#F1F3F7]">
              <div className="z-[15]">
                <div className="z-10 flex w-full items-center justify-between bg-white px-6 py-3">
                  <div className="">header</div>
                  <div className="flex items-center">
                    <div className="mr-6 flex items-center gap-x-6">
                      <Link href="https://disk.yandex.ru/d/tKpzWq2XQxjJKQ">
                        <Storage className="hover:text-[#3B82F6]" />
                      </Link>
                      <Questions className="hover:text-[#3B82F6]" />
                      <Mail className="hover:text-[#3B82F6]" />
                      <Links className="hover:text-[#3B82F6]" />
                      <Ball className="hover:text-[#3B82F6]" />
                      <Plus className="hover:text-[#3B82F6]" />
                    </div>
                    <div className="h-10 w-10 rounded-full border border-[#3B82F6]"></div>
                  </div>
                </div>
              </div>
              <div className="h-full w-full overflow-hidden">
                <div className="relative h-full w-full overflow-x-hidden overflow-y-scroll">
                  <div className="vertical-scrollbar scrollbar-lg flex h-full w-full flex-col space-y-7 overflow-y-auto px-6 py-8">
                    {children}
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
