import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body style={inter.style}>
        <div className="h-screen w-full overflow-hidden">
          <div className="relative flex h-screen w-full overflow-hidden">
            <div className="fixed inset-y-0 z-20 flex h-full w-[280px] flex-shrink-0 flex-grow-0 flex-col bg-white duration-300 md:relative md:ml-0 lg:ml-0">
              <div className="flex h-full w-full flex-1 flex-col"></div>
            </div>
            <main className="relative flex h-full w-full flex-col overflow-hidden bg-[#F1F3F7]">
              <div className="z-[15]">
                <div className="z-10 flex w-full items-center bg-white">
                  header
                </div>
              </div>
              <div className="h-full w-full overflow-hidden">
                <div className="relative h-full w-full overflow-x-hidden overflow-y-scroll">
                  <div className="vertical-scrollbar scrollbar-lg flex h-full w-full flex-col space-y-7 overflow-y-auto p-7">
                    {children}
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
